/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autentica;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.dateTime;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author Matiss-Study
 */
public class AutenticaForm extends javax.swing.JFrame {

    /**
     * Creates new form AutenticaForm
     */
    public AutenticaForm() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BikeID = new javax.swing.JComboBox<>();
        EmployeeID = new javax.swing.JComboBox<>();
        EmployeeLabel = new javax.swing.JLabel();
        BicycleLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        TimeStartBox = new javax.swing.JComboBox<>();
        TimeStartLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        TimeEndBox = new javax.swing.JComboBox<>();
        TimeEndLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        NotificationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        DatePicker = new org.jdesktop.swingx.JXDatePicker();
        CurrentTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BikeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BikeIDActionPerformed(evt);
            }
        });

        EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIDActionPerformed(evt);
            }
        });

        EmployeeLabel.setText("Employee");

        BicycleLabel.setText("Bicicle");

        TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Bike Booking System For Employees");
        TitleLabel.setToolTipText("");

        TimeStartBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeStartBoxActionPerformed(evt);
            }
        });

        TimeStartLabel.setText("Time Start");

        DateLabel.setText("Date");

        TimeEndBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeEndBoxActionPerformed(evt);
            }
        });

        TimeEndLabel.setText("Time End");

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        NotificationLabel.setBackground(new java.awt.Color(255, 102, 0));
        NotificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NotificationLabel.setText("NOTIFICATION");

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("START PROGRAM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CurrentTime.setText("asa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(CurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeLabel)
                            .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BikeID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BicycleLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(DateLabel)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeStartLabel)
                            .addComponent(TimeStartBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeEndLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TimeEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(SubmitButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(CurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BicycleLabel)
                                .addComponent(DateLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BikeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(TimeStartLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TimeStartBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(TimeEndLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TimeEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SubmitButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(NotificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIDActionPerformed

    }//GEN-LAST:event_EmployeeIDActionPerformed

    private void BikeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BikeIDActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_BikeIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        connectToAndAddComboBoxValuesEmployees("root", "parole");
        connectToAndAddComboBoxValuesBikes("root", "parole");   
        setTimeStart();
        setTimeFinish();
        
        
        Date date=new Date();    
        CurrentTime.setText(new SimpleDateFormat("yyyy.MM.dd  HH:mm").format(date));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TimeStartBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeStartBoxActionPerformed
 
    
    




    }//GEN-LAST:event_TimeStartBoxActionPerformed

    private void TimeEndBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeEndBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeEndBoxActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String eid = EmployeeID.getSelectedItem().toString();
        String bid = BikeID.getSelectedItem().toString();
        Date date = DatePicker.getDate();
        
        String dateR = date.toString();
        String dateN = dateR.substring(0, 10);
        String timeStart = TimeStartBox.getSelectedItem().toString();
        String timeEnd = TimeEndBox.getSelectedItem().toString();
        
        addBooking(eid,bid,dateN,timeStart,timeEnd);

    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutenticaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutenticaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutenticaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutenticaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutenticaForm().setVisible(true);
            }
        });
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BicycleLabel;
    private static javax.swing.JComboBox<String> BikeID;
    private javax.swing.JLabel CurrentTime;
    private javax.swing.JLabel DateLabel;
    private org.jdesktop.swingx.JXDatePicker DatePicker;
    private static javax.swing.JComboBox<String> EmployeeID;
    private javax.swing.JLabel EmployeeLabel;
    private javax.swing.JLabel NotificationLabel;
    private javax.swing.JButton SubmitButton;
    private static javax.swing.JComboBox<String> TimeEndBox;
    private javax.swing.JLabel TimeEndLabel;
    private static javax.swing.JComboBox<String> TimeStartBox;
    private javax.swing.JLabel TimeStartLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables




    public static void createConnection(String username, String password){
         try {
    Connection con = DriverManager.getConnection(
                         "jdbc:mysql://localhost:3306/employeedb?zeroDateTimeBehavior=convertToNull",
                         username,
                         password);

    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT * from emplyee");
    
    } catch (Exception ex){
    System.out.println(ex.toString());
        
}
    
    
    }
    
    
    
               public static void connectToAndAddComboBoxValuesEmployees(String username, String password){
        try {
    Connection con = DriverManager.getConnection(
                         "jdbc:mysql://localhost:3306/employeedb?zeroDateTimeBehavior=convertToNull",
                         username,
                         password);

    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT * from emplyee");
    
    
    while (rs.next()) {
        int workerID = rs.getInt("id");
        String wID = String.valueOf(workerID);
        AutenticaForm.EmployeeID.addItem(wID);
    }
    
    } catch (Exception ex){
    System.out.println(ex.toString());
        
}
             }
               
               
               
                 public static void connectToAndAddComboBoxValuesBikes(String username, String password){
        try {
    Connection con = DriverManager.getConnection(
                         "jdbc:mysql://localhost:3306/employeedb?zeroDateTimeBehavior=convertToNull",
                         username,
                         password);

    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT * from bikes");
    
    
    while (rs.next()) {
        int bikeID = rs.getInt("id");
        String bID = String.valueOf(bikeID);
        AutenticaForm.BikeID.addItem(bID);
    }
    
    } catch (Exception ex){
    System.out.println(ex.toString());
        
}
             }
   
     public void setTimeStart(){
      DateFormat df = new SimpleDateFormat("HH:mm");
Calendar cal = Calendar.getInstance();
cal.set(Calendar.HOUR_OF_DAY, 0);
cal.set(Calendar.MINUTE, 0);
cal.set(Calendar.SECOND, 0);
int startDate = cal.get(Calendar.DATE);
while (cal.get(Calendar.DATE) == startDate) {
    AutenticaForm.TimeStartBox.addItem(df.format(cal.getTime()));
    cal.add(Calendar.MINUTE, 30);
}
   
    }
     
     public void setTimeFinish(){
      DateFormat df = new SimpleDateFormat("HH:mm");
Calendar cal = Calendar.getInstance();
cal.set(Calendar.HOUR_OF_DAY, 0);
cal.set(Calendar.MINUTE, 0);
cal.set(Calendar.SECOND, 0);
int startDate = cal.get(Calendar.DATE);
while (cal.get(Calendar.DATE) == startDate) {
    AutenticaForm.TimeEndBox.addItem(df.format(cal.getTime()));
    cal.add(Calendar.MINUTE, 30);
}
        
    }
     
  public List<booking> bookingList = new ArrayList<>();

    public void addBooking(String eid,String bid,String d,String s, String e){
        
        booking booking1 = new booking(eid,bid,d,s,e);
        
        bookingList.add(booking1);
        System.out.println(bookingList.get(0).toString());
    }
 
}



